//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP45_eCanteenStock.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPP45_eCanteen : DbContext
    {
        public CPP45_eCanteen()
            : base("name=CPP45_eCanteen")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<W_Master_Item_Product> W_Master_Item_Product { get; set; }
        public DbSet<W_Master_Package> W_Master_Package { get; set; }
        public DbSet<W_Master_Type> W_Master_Type { get; set; }
        public DbSet<W_TR_Product> W_TR_Product { get; set; }
    }
}
