//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP45_eCanteenStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Master_Package
    {
        public int ID { get; set; }
        public int Pack_ID { get; set; }
        public string Pack_Des { get; set; }
        public Nullable<int> Pack_QTY { get; set; }
        public string Status { get; set; }
    }
}
