//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP45_eCanteenStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Master_Item_Product
    {
        public int ID { get; set; }
        public string Pro_ID { get; set; }
        public string Pro_Name { get; set; }
        public Nullable<int> Pro_Type { get; set; }
        public string Pro_Unit { get; set; }
        public Nullable<int> Pro_Pack { get; set; }
        public Nullable<double> Pro_Qty { get; set; }
        public string Pro_Barcode { get; set; }
        public Nullable<decimal> Pro_Price { get; set; }
        public Nullable<decimal> Pro_Cost { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Pro_Create_Date { get; set; }
        public Nullable<System.DateTime> Pro_Update_Date { get; set; }
        public string Create_By { get; set; }
    }
}
