//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP45_eCanteenStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_TR_Product
    {
        public int ID { get; set; }
        public string TR_Pro_ID { get; set; }
        public string TR_Status { get; set; }
        public string TR_Barcode { get; set; }
        public Nullable<int> TR_Pack { get; set; }
        public Nullable<double> TR_Qty { get; set; }
        public Nullable<System.DateTime> TR_Create_Date { get; set; }
        public Nullable<System.DateTime> TR_Update_Date { get; set; }
        public string TR_By { get; set; }
        public string Status { get; set; }
    }
}
